name: tiled_warfare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  random_name_generator: ^1.5.0
  xml: ^7.0.1
  logging: ^1.2.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/token/
    - assets/maps/
    - assets/maps/map0/
    